// Copyright (c) Microsoft Corporation. All rights reserved.

// Code generated by update-protocol-version. DO NOT EDIT.

package com.github.copilot

/**
 * The SDK protocol version.
 * This must match the version expected by the copilot-agent-runtime server.
 */
object SdkProtocolVersion:

  /** The current SDK protocol version. */
  val Version: Int = 3

  /** Gets the SDK protocol version. */
  def get: Int = Version
