# Code generated by update-protocol-version.ts. DO NOT EDIT.

#' SDK Protocol Version for the Copilot SDK.
#'
#' This must match the version expected by the copilot-agent-runtime server.
#' @export
SDK_PROTOCOL_VERSION <- 3L

#' Get the SDK protocol version.
#'
#' @return The protocol version number (integer).
#' @export
get_sdk_protocol_version <- function() {
  SDK_PROTOCOL_VERSION
}
