// Copyright (c) Microsoft Corporation. All rights reserved.

// Code generated by update-protocol-version. DO NOT EDIT.

/// The SDK protocol version.
/// This must match the version expected by the copilot-agent-runtime server.
pub const SDK_PROTOCOL_VERSION: u32 = 2;

/// Gets the SDK protocol version.
pub fn get_sdk_protocol_version() -> u32 {
    SDK_PROTOCOL_VERSION
}
