---------------------------------------------------------------------------------------------
--  Copyright (c) Microsoft Corporation. All rights reserved.
---------------------------------------------------------------------------------------------

-- Code generated by update-protocol-version. DO NOT EDIT.

-- | SDK protocol version constant.
-- This must match the version expected by the copilot-agent-runtime server.
module Copilot.SdkProtocolVersion
  ( sdkProtocolVersion
  ) where

-- | The SDK protocol version.
sdkProtocolVersion :: Int
sdkProtocolVersion = 2
