// Code generated by update-protocol-version.ts. DO NOT EDIT.

namespace CopilotSDK.Supercharged.FSharp

/// Provides the SDK protocol version.
/// This must match the version expected by the copilot-agent-runtime server.
[<RequireQualifiedAccess>]
module SdkProtocolVersion =

    /// The SDK protocol version.
    [<Literal>]
    let Version = 3

    /// Gets the SDK protocol version.
    let getVersion () = Version
