/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/
package com.github.copilot

// Code generated by update-protocol-version. DO NOT EDIT.

import groovy.transform.CompileStatic

/**
 * The SDK protocol version.
 * This must match the version expected by the copilot-agent-runtime server.
 */
@CompileStatic
final class SdkProtocolVersion {
    static final int SDK_PROTOCOL_VERSION = 3

    private SdkProtocolVersion() {}

    static int get() {
        SDK_PROTOCOL_VERSION
    }
}
