/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

// Code generated by update-protocol-version. DO NOT EDIT.

package com.github.copilot

/**
 * The SDK protocol version.
 * This must match the version expected by the copilot-agent-runtime server.
 */
const val SDK_PROTOCOL_VERSION: Int = 2

/**
 * Gets the SDK protocol version.
 * @return The protocol version number
 */
fun getSdkProtocolVersion(): Int = SDK_PROTOCOL_VERSION
