package GitHub::Copilot::SdkProtocolVersion;
# Copyright (c) Microsoft Corporation. All rights reserved.

# Code generated by update-protocol-version. DO NOT EDIT.

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw($SDK_PROTOCOL_VERSION get_sdk_protocol_version);

=head1 NAME

GitHub::Copilot::SdkProtocolVersion - SDK protocol version constant

=head1 DESCRIPTION

The SDK protocol version. This must match the version expected by the
copilot-agent-runtime server.

=cut

our $SDK_PROTOCOL_VERSION = 3;

sub get_sdk_protocol_version {
    return $SDK_PROTOCOL_VERSION;
}

1;
