#!/usr/bin/env bash
# Code generated by update-protocol-version.ts. DO NOT EDIT.
#
# SDK Protocol Version for the Copilot SDK.
# This must match the version expected by the copilot-agent-runtime server.

COPILOT_SDK_PROTOCOL_VERSION=3

# Gets the SDK protocol version.
# Usage: version=$(copilot_get_sdk_protocol_version)
copilot_get_sdk_protocol_version() {
    echo "$COPILOT_SDK_PROTOCOL_VERSION"
}
