--- SDK Protocol Version
-- This must match the version expected by the copilot-agent-runtime server.
-- Code generated by update-protocol-version. DO NOT EDIT.

local M = {}

--- The SDK protocol version constant.
M.SDK_PROTOCOL_VERSION = 3

--- Returns the SDK protocol version.
-- @return number The protocol version
function M.get()
    return M.SDK_PROTOCOL_VERSION
end

return M
