% tool_example.m  --  Register custom tools with the Copilot agent
%
% Demonstrates how to define tools that the agent can invoke during a
% conversation. The SDK calls your MATLAB function and returns the result.

%% Define a weather tool
weatherTool = copilot.DefineTool( ...
    'Name',        'get_weather', ...
    'Description', 'Return the current weather for a city.', ...
    'Parameters',  struct( ...
        'type', 'object', ...
        'properties', struct( ...
            'city', struct('type', 'string', 'description', 'City name')), ...
        'required', {{'city'}}), ...
    'Handler', @getWeather);

%% Define a calculator tool
calcTool = copilot.DefineTool( ...
    'Name',        'calculate', ...
    'Description', 'Evaluate a MATLAB expression.', ...
    'Parameters',  struct( ...
        'type', 'object', ...
        'properties', struct( ...
            'expression', struct('type', 'string', 'description', 'MATLAB expression')), ...
        'required', {{'expression'}}), ...
    'Handler', @calculate);

%% Create client and session with tools
client = copilot.CopilotClient();
client.start();

config = copilot.SessionConfig( ...
    'Model', 'gpt-5', ...
    'Tools', {weatherTool, calcTool});
session = client.createSession(config);

resp = session.sendAndWait( ...
    copilot.MessageOptions('Prompt', 'What is the weather in Seattle?'));
fprintf('Agent said:\n%s\n', resp.Content);

session.disconnect();
client.stop();

%% Local tool implementations
function result = getWeather(params)
    result = struct( ...
        'city',        params.city, ...
        'temperature', '18C', ...
        'condition',   'Partly cloudy');
end

function result = calculate(params)
    try
        val = eval(params.expression); %#ok<EVLC>
        result = struct('result', val);
    catch me
        result = struct('error', me.message);
    end
end
