# frozen_string_literal: true

# Copyright (c) Microsoft Corporation. All rights reserved.

# Code generated by update-protocol-version. DO NOT EDIT.

module Copilot
  # The SDK protocol version.
  # This must match the version expected by the copilot-agent-runtime server.
  SDK_PROTOCOL_VERSION = 3

  # @return [Integer] the SDK protocol version number
  def self.sdk_protocol_version
    SDK_PROTOCOL_VERSION
  end
end
