/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/
package com.github.copilot;

// Code generated by update-protocol-version. DO NOT EDIT.

/**
 * The SDK protocol version.
 * This must match the version expected by the copilot-agent-runtime server.
 */
public final class SdkProtocolVersion {
    public static final int SDK_PROTOCOL_VERSION = 3;

    private SdkProtocolVersion() {}

    public static int get() {
        return SDK_PROTOCOL_VERSION;
    }
}
